### ISSUE TITLE
floor-seq in README is not correct.

### ISSUE THREAD

**Issue by ghost** [gfZeng/time.clj#6]
the demo:
`(take 1 (-> (t/date) (t/floor-seq [1 :minute])))` will give 
UnsupportedOperationException nth not supported on this type: Date  clojure.lang.RT.nthFrom (RT.java:947)..

in the README.md should be (->> (t/date) (t/floor-seq [1 :minute]))

**Comment by spagreeks** [comment]
fixed, thanks
